# -*- coding: utf-8 -*-
"""alternate_numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16_wlziaC87Kxc8xQI6si6iYu-Om0ZvQR
"""

a=[-5, -2, 5, 2, -4, -8,0]
#Splitting an array in two arrays
pos = [num for num in a if num >= 0]#pos array conatain all the positive number and consider 0 as positve number
neg = [num for num in a if num < 0]#neg  array contain all the negative number
result = []# this is an empty array
#Adding positive and then negative number one by one  in result by using for loop
for i in range(min(len(pos),len(neg))):
      result.append(pos[i])
      result.append(neg[i])
#extend method add the remaining elements at last
if len(pos)>len(neg) :
      result.extend(pos[len(neg):])
if len(neg)>len(pos):
      result.extend(neg[len(pos):])
print(result)


#space complexity=O(n)
#time complexity=O(n)